version: "3.8"

services:
  lab-monitoring:
    build: .
    #    deploy:
    #      resources:
    #        reservations:
    #          devices:
    #            - driver: nvidia
    #              count: all
    #              capabilities: [gpu]
    #    runtime: nvidia
    container_name: lab-monitoring-app
    ports:
      - "5001:5000"
    volumes:
      - ./:/app # mount everything inside modularized (keep for developement)
      - ./web/static/incompliances:/app/web/static/incompliances
      - ./yolo_models:/app/yolo_models
    env_file:
      - .env # This tells Docker Compose to load environment variables from the .env file
    environment:
      - FLASK_APP=app.py
      - PYTHONUNBUFFERED=1 # To have print statements to docker logs
      - FLASK_ENV=${FLASK_ENV}
      - PYTHONPATH=${PYTHONPATH}
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped
    devices:
      - /dev/video0:/dev/video0
    privileged: true
    depends_on:
      postgres:
        condition: service_healthy # Ensure the DB is healthy before starting app

  postgres:
    image: postgres:13
    container_name: lab-monitoring-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@labcomply.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8082:80"
    depends_on:
      - postgres # your PostgreSQL container name
    volumes:
      - ./pgadmin_config/servers/servers.json:/pgadmin4/servers.json

volumes:
  postgres_data:
